using System;
using System.Collections.Generic;
using System.Text;

namespace NetArchTest.TestStructure.Metrics
{
    // This class was generated by GPT-4 Turbo :D
    public class ClassLarge
    {
        // Fields
        private string owner;
        private double balance;
        private double interestRate;

        // Constructors
        public ClassLarge()
        {
            owner = "Unknown";
            balance = 0.0;
            interestRate = 0.0;
        }

        public ClassLarge(string owner, double balance, double interestRate)
        {
            this.owner = owner;
            this.balance = balance;
            this.interestRate = interestRate;
        }

        // Methods
        public void Deposit(double amount)
        {
            // Check if the amount is positive
            if (amount > 0)
            {
                // Add the amount to the balance
                balance += amount;
                // Print a confirmation message
                Console.WriteLine("You have deposited {0:C} to your account.", amount);
            }
            else
            {
                // Print an error message
                Console.WriteLine("Invalid amount. Please enter a positive number.");
            }
        }

        public void Withdraw(double amount)
        {
            // Check if the amount is positive
            if (amount > 0)
            {
                // Check if the amount is less than or equal to the balance
                if (amount <= balance)
                {
                    // Subtract the amount from the balance
                    balance -= amount;
                    // Print a confirmation message
                    Console.WriteLine("You have withdrawn {0:C} from your account.", amount);
                }
                else
                {
                    // Print an error message
                    Console.WriteLine("Insufficient funds. You cannot withdraw more than your balance.");
                }
            }
            else
            {
                // Print an error message
                Console.WriteLine("Invalid amount. Please enter a positive number.");
            }
        }

        public void Transfer(double amount, ClassLarge other)
        {
            // Check if the other account is not null
            if (other != null)
            {
                // Check if the amount is positive
                if (amount > 0)
                {
                    // Check if the amount is less than or equal to the balance
                    if (amount <= balance)
                    {
                        // Subtract the amount from the balance
                        balance -= amount;
                        // Add the amount to the other account's balance
                        other.balance += amount;
                        // Print a confirmation message
                        Console.WriteLine("You have transferred {0:C} to {1}'s account.", amount, other.owner);
                    }
                    else
                    {
                        // Print an error message
                        Console.WriteLine("Insufficient funds. You cannot transfer more than your balance.");
                    }
                }
                else
                {
                    // Print an error message
                    Console.WriteLine("Invalid amount. Please enter a positive number.");
                }
            }
            else
            {
                // Print an error message
                Console.WriteLine("Invalid account. Please enter a valid account.");
            }
        }

        public void ApplyInterest()
        {
            // Calculate the interest amount
            double interest = balance * interestRate / 100;
            // Add the interest amount to the balance
            balance += interest;
            // Print a confirmation message
            Console.WriteLine("You have earned {0:C} in interest.", interest);
        }

        // Override ToString method
        public override string ToString()
        {
            return $"Owner: {owner}, Balance: {balance:C}, Interest Rate: {interestRate}%";
        }
    }
}
